version: '3.2'

services:
  fastapi:
    build:
      context: fastapi/
      dockerfile: Dockerfile
    container_name : fastapi
    command: gunicorn -k uvicorn.workers.UvicornWorker --access-logfile ./gunicorn-access.log main:app --bind 0.0.0.0:8000 --workers 2 --daemon
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
